services:
  - type: web
    name: ai-knowledge-worker-backend
    env: docker
    plan: free
    dockerfilePath: ./docker/Dockerfile
    buildContext: .
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: NEWS_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: ALPHA_VANTAGE_API_KEY
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_ALG
        sync: false
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        sync: false
      - key: YAHOO_API_KEY
        sync: false
      - key: YAHOO_API_HOST
        sync: false
